apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.163.178.95:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaINvJVcfLsQ6rBvFfiSwabhAVKWhRlV44qOWBb3We/0BaEp5eCpteCpheCngKWggBEAEaBgjF
      hc2cBiIKc3lzY2hhbm5lbCpAMDdlMGM5MzQ3ZDhlZTMzMzdhZWNmNTEyNmJjODM1NjBmMmEwY2Vi
      Y2FlZGEwN2Q2ZWExYjZiMjA5MDIzZmQ3MxIaEhhaH+rJp7NXY3qCBcsIqSOt5u2iJbtNov8Sm10K
      mF0SlV0SkysKB09yZGVyZXIShysSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVTzkxREdhSDQzVzdtV2FLT25Md3JQbFJqclM0d0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBNU1UTTFPVE0yV2hjTk1qVXdPVEk0TVRNMU9UTTJX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJBT0pX
      VTdMeStIemtkeTJXeDErQzlBbERqWjA4azZFN3JiM0lSL2V6eXEramJ5Nld0WDcKYTZiWnJIWmlO
      b0pjNzlMY2UzNXpNNktwRXZVaTVKUjBSaXVqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU1JNSmQwNitHcWtDOUNZN2FtakVUVW1j
      d085akFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTdFeTBydjVnUFVMcURuYXA1TEtzUnhsVm9F
      RHYyVXhMN2FTVVpzNngKdmpNQ0lITnlyUHZIcmZuRkFabnVFNnNSZkluS0N5Lzk5eGFZcmVYOWtU
      alMxYlM4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0RENDQW9lZ0F3SUJBZ0lVVVhUYnFNZVNnaUZFUjEwbERjM25qczhlL0Zjd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBNU1UUXdOakF3V2hjTk1q
      TXhNakE1TVRReE1UQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFeWhEQnpyUm5OMXBhYnR3RVlIQkJFanlJTm5E
      MHEyYWEKdEF1WVJOdktPUStpYWtCN2p5VlFzaWxIVXRnZVl1NFpnY1pkK0RPRjQ5YzREb3BtMUxy
      ZGM2T0NBUk13Z2dFUApNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRM3BUMmgydUx3Cjc5cjZ6andsVnlZSUYxaHZrakFmQmdOVkhTTUVHREFXZ0JT
      Uk1KZDA2K0dxa0M5Q1k3YW1qRVRVbWN3TzlqQWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kx
      aU56Um1OVGczTnprdE9XTnhaamN3Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1G
      aVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkds
      aGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdO
      b1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05I
      QURCRQpBaUJ6V2dPd3V6VzEvbGZlUitUWWhnc0tZUTZ6RXlDZ2JxeEIzZWJLekRrakV3SWdXTy9l
      SUJJYkVxdXF2dVF4ClM3YWZzY2xDNVVJRGU1dmErM0JNOVorR3VRcz0KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVTzkxREdhSDQzVzdtV2FLT25Md3JQbFJqclM0d0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpBNU1UTTFPVE0yV2hjTk1qVXdPVEk0
      TVRNMU9UTTJXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJBT0pXVTdMeStIemtkeTJXeDErQzlBbERqWjA4azZFN3JiM0lSL2V6eXEramJ5Nld0WDcK
      YTZiWnJIWmlOb0pjNzlMY2UzNXpNNktwRXZVaTVKUjBSaXVqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU1JNSmQwNitHcWtDOUNZ
      N2FtakVUVW1jd085akFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTdFeTBydjVnUFVMcURuYXA1
      TEtzUnhsVm9FRHYyVXhMN2FTVVpzNngKdmpNQ0lITnlyUHZIcmZuRkFabnVFNnNSZkluS0N5Lzk5
      eGFZcmVYOWtUalMxYlM4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIW
      EgwKCgoGVjFfNF8yEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoIZXRjZHJhZnQS
      4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlEQkRDQ0FxdWdBd0lCQWdJVVJvQ1hMeEFvS3g2Ykt4UEdIM3NvaHU5NS9kc3dD
      Z1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURW
      UVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1qQTVNVFF3TmpBd1doY05N
      ak14TWpBNU1UUXhNVEF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVO
      VEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxF
      d2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpa
      WFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVM2YjQxVVFhamZvdWVQMi9rN3FO
      dlo0b0VpCi9URk90RGhWTm0rQk1RUVlrNTVMdEVKSW5DYUhQcURGQWw1YmJIWmlZYVNmalVzVm8w
      VnEwWkZqM3hEa280SUIKTWpDQ0FTNHdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01C
      UUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERn
      UVdCQlM2SkozNlQrYjhaSGZhb21FaTdpaUNjSGpvCnN6QWZCZ05WSFNNRUdEQVdnQlNSTUpkMDYr
      R3FrQzlDWTdhbWpFVFVtY3dPOWpCQkJnTlZIUkVFT2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JI
      bGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JB
      WUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxD
      Sm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      aUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlB
      Vyt6NnRrdW0yWVNHLwpjbnc2TUozc3h5T3FIOXZ6WlZrMEhjMDl4K25xNGdJZ09UODZSeHdsZXJs
      SW82OFJ1cWs3KzQxRkh2K3FvS0xSCklPZFdKMnpHWG1JPQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQkRDQ0FxdWdBd0lCQWdJVVJv
      Q1hMeEFvS3g2Ykt4UEdIM3NvaHU5NS9kc3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJo
      TUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0Rn
      WURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhR
      dwpIaGNOTWpJeE1qQTVNVFF3TmpBd1doY05Nak14TWpBNU1UUXhNVEF3V2pCeE1Rc3dDUVlEVlFR
      R0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFR
      S0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFN
      QkJ3TkNBQVM2YjQxVVFhamZvdWVQMi9rN3FOdlo0b0VpCi9URk90RGhWTm0rQk1RUVlrNTVMdEVK
      SW5DYUhQcURGQWw1YmJIWmlZYVNmalVzVm8wVnEwWkZqM3hEa280SUIKTWpDQ0FTNHdEZ1lEVlIw
      UEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpB
      TUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlM2SkozNlQrYjhaSGZhb21FaTdpaUNjSGpv
      CnN6QWZCZ05WSFNNRUdEQVdnQlNSTUpkMDYrR3FrQzlDWTdhbWpFVFVtY3dPOWpCQkJnTlZIUkVF
      T2pBNGdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NIRzl5WkdWeVpYSXhMblZ3
      WjNKaFpHVXVkWEJuY21GawpaUzVqYjIwd2JBWUlLZ01FQlFZSENBRUVZSHNpWVhSMGNuTWlPbnNp
      YUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpCkxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSnZjbVJs
      Y21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm8KWmk1VWVYQmxJam9pYjNKa1pYSmxjaUo5
      ZlRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBVyt6NnRrdW0yWVNHLwpjbnc2TUozc3h5T3FIOXZ6
      WlZrMEhjMDl4K25xNGdJZ09UODZSeHdsZXJsSW82OFJ1cWs3KzQxRkh2K3FvS0xSCklPZFdKMnpH
      WG1JPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAKGgZBZG1p
      bnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4S
      BAoCMnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0
      ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIa
      BkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1p
      bnMSuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4SsRcKD21h
      bnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1ASgQYtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVKNEVnTE11L1FTdmpJ
      dE5kc0wvQ0x2ODI5a3d3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5C
      Z05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5Z
      VzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdI
      aGNOTWpJeE1qQTVNVFF3TURVMVdoY05NalV3T1RJNE1UUXdNRFUxV2pCa01Rc3dDUVlEVlFRRwpF
      d0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJn
      TlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNt
      VnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJONmRsY2dER2lSZEZh
      YkhkdlZ3cjVlbFd6c1U4M2pINmtpdApyV013d29MVE4zRms1OUVEOWtTeCt1TUFDN1hKek9xaVQ2
      OWFNVjltZ0tCbzluSUw0RnFqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVDdRREUvM0lsbzZyWGkKUVBDaEQwc0VhdXBXZ0RBS0Jn
      Z3Foa2pPUFFRREFnTklBREJGQWlFQSs1WlVSemJPMnIyWnNvcVpKaXZ1TEtxZwp6TW9TMkh4TmNy
      bFVMcDNNZGdVQ0lIKzlFZ0F6ZTZEZnNPeGdteERrMEFqTFllMm1ieENDUmZ5bXp2Y2Q1blhwCi0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURFVENDQXJlZ0F3SUJBZ0lVUkczMUpxUWRLQk04RjRUckhCczc1ZWRvcTZNd0NnWUlLb1pJemow
      RUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFV
      RUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFN
      TUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNakE1TVRRd09EQXdXaGNOTWpN
      eE1qQTVNVFF4TXpBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RFVFEzTGpN
      NEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJekFNQmdO
      VkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURWUVFEREJa
      QlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkkKemow
      REFRY0RRZ0FFRWswMUdERjFyclMvQ0lXNkt3RkJzRXNDN0Y5Y205ekh2THBTQ0kxZUp6WjR3VFUv
      K2p6ZgpKdFJmWHdOTDVmUWhhOVRTZnZmOEMzaEtYTVNLWk94SmhxT0NBU0l3Z2dFZU1BNEdBMVVk
      RHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUZGNCNnE2emo4
      UHFRY2RmWXRZZm1IQnBoeGN6QWYKQmdOVkhTTUVHREFXZ0JUN1FERS8zSWxvNnJYaVFQQ2hEMHNF
      YXVwV2dEQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwMk9HUTVOVGRrWkRrMkxYaHdibWMy
      TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElqb2lkSEox
      WlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJXRnVkV1po
      WTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFdaaApZM1Ix
      Y21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFRREFnTklB
      REJGCkFpRUFtZlI1cWlYK2VOMHQxc2JnSDdkZEh1UEFVV3VkYW10RnR1TDllOTNVSDQ4Q0lIWmRr
      bllpZytCSnQ5ZFYKZDVFejBCMnNpcDZaNWlCaGpIUDBkdWVBOVdhRgotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQ0REQ0NBYktnQXdJQkFnSVVKNEVnTE11L1FTdmpJdE5kc0wvQ0x2ODI5a3d3Q2dZSUtvWkl6
      ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdB
      MVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZC
      QU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qQTVNVFF3TURVMVdoY05N
      alV3T1RJNE1UUXdNRFUxV2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlh
      V05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxj
      akVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlB
      Z0VHQ0NxR1NNNDlBd0VIQTBJQUJONmRsY2dER2lSZEZhYkhkdlZ3cjVlbFd6c1U4M2pINmtpdApy
      V013d29MVE4zRms1OUVEOWtTeCt1TUFDN1hKek9xaVQ2OWFNVjltZ0tCbzluSUw0RnFqUWpCQU1B
      OEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JC
      VDdRREUvM0lsbzZyWGkKUVBDaEQwc0VhdXBXZ0RBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQSs1
      WlVSemJPMnIyWnNvcVpKaXZ1TEtxZwp6TW9TMkh4TmNybFVMcDNNZGdVQ0lIKzlFZ0F6ZTZEZnNP
      eGdteERrMEFqTFllMm1ieENDUmZ5bXp2Y2Q1blhwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      GgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1cmVyTVNQ
      EAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21hbnVmYWN0
      dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51ZmFj
      dHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFudWZh
      Y3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQErcUEqwU
      EqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrVENDQVo2
      Z0F3SUJBZ0lVR0VDUkZqT2NPNnpOMjRrdXByaVA5VDNSR0lBd0NnWUlLb1pJemowRUF3SXcKV2pF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5
      TFc1bGREQWVGdzB5Ck1qRXlNRGt4TkRBeU1UQmFGdzB5TlRBNU1qZ3hOREF5TVRCYU1Gb3hDekFK
      QmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2
      YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1
      WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUUthWnBMVmIrYWZWQmQrUy94
      a0Nwend4UTkyNjM2bmZ1endiUGx6Uk85aksxT0JQaVJxRUxiWkN4OGcvSlUKRGhLM2JiTHFSbHlq
      dTM4Si9XbjJiaW9abzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FF
      QXdJQnBqQWRCZ05WSFE0RUZnUVVqTGxMRU1WMmFhYkdiM0V6a1lzZWVGNVdDeWt3Q2dZSUtvWkl6
      ajBFCkF3SURTUUF3UmdJaEFJNzl1bzAxTnltSG1xRUVHT1JhUnRJN0JxZjIreTFheXE1Z1kwTUhF
      anh2QWlFQXI5RkYKYTR3VjE2MGJGRmdlRDc2Qmg0QnJNaEdySnFVM2RERWFHOW1oYWhNPQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlD
      N1RDQ0FwU2dBd0lCQWdJVUZjQVduaGJ3M2Z6RjMwUVZLQlhXT21UNDRBVXdDZ1lJS29aSXpqMEVB
      d0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZ
      WEp5YVdWeUxXNWxkREFlRncweQpNakV5TURreE5EQTVNREJhRncweU16RXlNRGt4TkRFME1EQmFN
      SGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5TWIyNWti
      MjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0R0ExVUVD
      eE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhRd1dUQVRC
      Z2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUMWE2WU1la1FwQlV1NnBnemtvWjNNCmErcHJx
      V3dFTnVMQ3EvektwWU9tYnlldzRqejRKOHczd0RNN2JueVhxNkVlVXBFN2pqanc4WVZsdTZOYWtl
      R3kKbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FDTUFBd0hR
      WURWUjBPQkJZRQpGRzdyUndSVTRwbStOeVNVbzJSb2xHN2dhRHI3TUI4R0ExVWRJd1FZTUJhQUZJ
      eTVTeERGZG1tbXhtOXhNNUdMCkhuaGVWZ3NwTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2YjJ4ekxU
      WTVORGhpTkRnM1pqWXRaamczTlRRd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5Y3lJNmV5
      SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1UVdabWFX
      eHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9pUVdSdGFX
      NUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkKS29aSXpq
      MEVBd0lEUndBd1JBSWdkQ09QSHFLUzVLQmttTHlGRG1zMGlYRis1UG0zbnBVU3BpUEJod2hIWTlz
      QwpJR0VSRUdRUjRNNXN3ZlZSYW1nZFkvcDVqQ0NBazZCelVNVk83Ylh2TDl3aQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQitUQ0NBWjZnQXdJQkFnSVVHRUNSRmpPY082ek4yNGt1cHJpUDlUM1JHSUF3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFeU1Ea3hOREF5TVRCYUZ3MHlOVEE1TWpn
      eE5EQXlNVEJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpB
      TkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3
      T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFR
      S2FacExWYithZlZCZCtTL3hrQ3B6d3hROTI2MzZuZnV6d2JQbHpSTzlqSzFPQlBpUnFFTGJaQ3g4
      Zy9KVQpEaEszYmJMcVJseWp1MzhKL1duMmJpb1pvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgv
      TUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVWpMbExFTVYyYWFiR2IzRXprWXNl
      ZUY1V0N5a3dDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQUk3OXVvMDFOeW1IbXFFRUdPUmFSdEk3
      QnFmMit5MWF5cTVnWTBNSEVqeHZBaUVBcjlGRgphNHdWMTYwYkZGZ2VENzZCaDRCck1oR3JKcVUz
      ZERFYUc5bWhhaE09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNAoGQWRtaW5z
      EioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1l
      bnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiMwoHUmVhZGVycxIo
      Eh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0S
      EhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////
      DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1u
      ZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZW
      MV80XzMSABoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQ
      AhoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
