apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: solo

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.163.178.95:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIGJwSm8XowSsSPNflnO9QyPuQYOcHW3/fYYpm4S3DJwyErxMCrlMCrZMCngKWggBEAEaBgiD
      1bmdBiIKc3lzY2hhbm5lbCpAZDJiMTI4NjRlZTg3ZmExNDQ0YzRmNzk2NjUyNDEzMDg2NjI5NTAx
      ZDczM2I2Y2RiZDY2MDNmNjM3MzYyZTAxYRIaEhilOZLo1gWI7nXMX6eR1cbMOnraXlezAdMSuUsK
      tksSs0sSsRkKB09yZGVyZXISpRkS0hYKDnN1cHBseWNoYWluTVNQEr8WGssUCgNNU1ASwxQSuBQS
      tRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVZktOTHpHT1Jpc2ZKNStUSzkvQzdsdkR2VFpNd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl4TWpNd01EUXhNekEzV2hjTk1qVXhNREU1TURReE16QTNX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJMQ0hW
      RWtvNEloL1NNRUd6cTU2eDIxRURuanl0akhHSWU2VHZLN1pxY1V1YUwzb0FIZSsKa1p6QU9CYnJu
      ZkdqaFptOWV1Q0FZWkhGM0tMWmJyZ2VDRGlqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0FaUEtIME9FZlVBRGp0ckU1WlJ0WnZX
      MVV3REFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQW00MUswcEdCNHJHY1ZYV0lNS2M3NWg3TjBV
      TlVnR0t3TVVqNTFDZkIKNlRvQ0lRQ0xjejI2bjJuWWltUThnQWRQcVpaVS9wNUxDNzF4c3lQWmxH
      ckY5OTNlT0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKiCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNERDQ0FvZWdBd0lCQWdJVUZ0K2NoSmI3WTNzRkliVFZab3VNTlQybWQv
      RXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1qTXdNRFF4T0RBd1do
      Y05Nak14TWpNd01EUXlNekF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXZxSDNrWDRNemNzNHcxaWVndEhXR3I1
      eDlHdG5HQk5pCjVNcVo1MnkrNTdMbGRFUENIcEh4SU5BUWk5cG5jdWhGWTFiZ3JPUklFVnVBVmYx
      MDBmMEpqcU9DQVJNd2dnRVAKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCU2d2YzRaVU1KMQp0UG84emZpRmM2cXdpa05QdmpBZkJnTlZIU01FR0RB
      V2dCU0FaUEtIME9FZlVBRGp0ckU1WlJ0WnZXMVV3REFqCkJnTlZIUkVFSERBYWdoaGpZUzEwYjI5
      c2N5MWlOelJtTlRnM056a3Ribmg0ZUdnd2dZa0dDQ29EQkFVR0J3Z0IKQkgxN0ltRjBkSEp6SWpw
      N0ltRmlZV011YVc1cGRDSTZJblJ5ZFdVaUxDSmhaRzFwYmlJNkluUnlkV1VpTENKbwpaaTVCWm1a
      cGJHbGhkR2x2YmlJNklpSXNJbWhtTGtWdWNtOXNiRzFsYm5SSlJDSTZJa0ZrYldsdVFITjFjSEJz
      CmVXTm9ZV2x1TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhrak9QUVFE
      QWdOSEFEQkUKQWlCdWloVVFDeVEwbm5kYnBIbVpPemc4NnhXVmU5WnlHS1hwTFJPaW9SNC9xd0ln
      RFE2MWhHTWpUY1NZR3dwcgpTcTlOYWRTcW1vaTNRRzdIUXVqWDNOMXhkNlU9Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkr1BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVWZLTkx6R09SaXNmSjUrVEs5L0M3bHZEdlRaTXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJeE1qTXdNRFF4TXpBM1doY05NalV4
      TURFNU1EUXhNekEzV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCTENIVkVrbzRJaC9TTUVHenE1NngyMUVEbmp5dGpIR0llNlR2SzdacWNVdWFMM29B
      SGUrCmtaekFPQmJybmZHamhabTlldUNBWVpIRjNLTFpicmdlQ0RpalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlNBWlBLSDBPRWZV
      QURqdHJFNVpSdFp2VzFVd0RBSwpCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUFtNDFLMHBHQjRyR2NW
      WFdJTUtjNzVoN04wVU5VZ0dLd01VajUxQ2ZCCjZUb0NJUUNMY3oyNm4ybllpbVE4Z0FkUHFaWlUv
      cDVMQzcxeHN5UFpsR3JGOTkzZU9BPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlu
      cyI3CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI3CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI4CgZBZG1pbnMSLhIkCAESIBIIEgYIARICCAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1p
      bnMiOwoLRW5kb3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoG
      QWRtaW5zKgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0
      Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlu
      cxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMhIAGgZBZG1pbnMaIQoNQ29uc2Vuc3VzVHlw
      ZRIQEgYKBHNvbG8aBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIi
      CgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRt
      aW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      KgZBZG1pbnMSuS8KC0NvbnNvcnRpdW1zEqkvEt4uChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0SxC4S
      sRcKD21hbnVmYWN0dXJlck1TUBKdFxqlFQoDTVNQEp0VEpIVEo8VCg9tYW51ZmFjdHVyZXJNU1AS
      gQYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVWaVFSM1ll
      VGVwL21BbFJDYUtKK2I2L2lxbnN3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBn
      eER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFR
      S0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kx
      dVpYUXdIaGNOTWpJeE1qTXdNRFF4TkRJMVdoY05NalV4TURFNU1EUXhOREkxV2pCa01Rc3dDUVlE
      VlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4
      RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1po
      WTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJPUWdMaVNi
      Y2ZJU0hRQllzNTdmMGVnYm9Ea2JPT05hM2NIYgpJc2U3V0V2NEs3ZUtkaXIrK0hvdndQdnRIUlNu
      LzBOeFhqcFJoTzhJbnA1SXlnSXBsNFNqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lE
      VlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUzl4VGVhNUtOTVlOVlkKVkIreHh3KzM1aVha
      bnpBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQXU2eDM3Zmg0czRjZDF2dDdndnpRa3hFTwpGc2dU
      dXRqajViNGs2RnZIdHJrQ0lGdHV0Q00vQkROTFp0U3didWZmK2E5SWdHa0R0TSswdm4xbFFiWFRn
      b3NECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSURFRENDQXJlZ0F3SUJBZ0lVZWtPakV5ZkhYNmY4Rnk5UmF6VTlmTzZDUUUwd0NnWUlL
      b1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBN
      QTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFC
      Z05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qSXhNak13TURReU1EQXdX
      aGNOTWpNeE1qTXdNRFF5TlRBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hHakFZQmdOVkJBY1RF
      VFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpabUZqZEhWeVpYSXhJ
      ekFNQmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNtVnlNUjh3CkhRWURW
      UVFEREJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtv
      WkkKemowREFRY0RRZ0FFMURxd0ZML1dzWERITlpKcU81eUpUcW4yR0RiTitvS3JKUDk2a3pzbkpz
      UnRLbnlCQVRtQgpUSUZNTVJkRnNLcFJHQVU0T3ltZkVoK3FIZlZXTUZrWnc2T0NBU0l3Z2dFZU1B
      NEdBMVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSeWNV
      Wm4yazFKdlRTZkdZTmh6cHNtK0tJVGFEQWYKQmdOVkhTTUVHREFXZ0JTOXhUZWE1S05NWU5WWVZC
      K3h4dyszNWlYWm56QWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwMk9HUTVOVGRrWkRrMkxX
      WjRaRGh4TUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllXSmhZeTVwYm1sMElq
      b2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXUKSWpvaWJX
      RnVkV1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFiV0Z1ZFda
      aApZM1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRBS0JnZ3Foa2pPUFFR
      REFnTkhBREJFCkFpQVViZWt5eEJUVzJJdk5yeVpDQ3UvV2tYdmV3V2x2SmhiL1V4NHZ3bFZjWndJ
      Z0lvWUR0ZjYycFozaDRob2QKUWY4aFc4WVpkMU0vazMrdXFHblJVS3ZibWdzPQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKgQYtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQ0REQ0NBYktnQXdJQkFnSVVWaVFSM1llVGVwL21BbFJDYUtKK2I2L2lxbnN3Q2dZ
      SUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxqYURF
      UE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4SERB
      YUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJeE1qTXdNRFF4TkRJ
      MVdoY05NalV4TURFNU1EUXhOREkxV2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3
      R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdO
      MGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVsZERCWk1CTUcKQnlx
      R1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJPUWdMaVNiY2ZJU0hRQllzNTdmMGVnYm9Ea2JPT05h
      M2NIYgpJc2U3V0V2NEs3ZUtkaXIrK0hvdndQdnRIUlNuLzBOeFhqcFJoTzhJbnA1SXlnSXBsNFNq
      UWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVk
      RGdRV0JCUzl4VGVhNUtOTVlOVlkKVkIreHh3KzM1aVhabnpBS0JnZ3Foa2pPUFFRREFnTklBREJG
      QWlFQXU2eDM3Zmg0czRjZDF2dDdndnpRa3hFTwpGc2dUdXRqajViNGs2RnZIdHJrQ0lGdHV0Q00v
      QkROTFp0U3didWZmK2E5SWdHa0R0TSswdm4xbFFiWFRnb3NECi0tLS0tRU5EIENFUlRJRklDQVRF
      LS0tLS0KGgZBZG1pbnMiOQoGQWRtaW5zEi8SJQgBEiESCBIGCAESAggAGhUSEwoPbWFudWZhY3R1
      cmVyTVNQEAEaBkFkbWlucyI8CgtFbmRvcnNlbWVudBItEiMIARIfEggSBggBEgIIABoTEhEKD21h
      bnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1JlYWRlcnMSLRIjCAESHxIIEgYIARICCAAaExIRCg9t
      YW51ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdXcml0ZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoP
      bWFudWZhY3R1cmVyTVNQGgZBZG1pbnMqBkFkbWlucxKyFgoKY2Fycmllck1TUBKjFhq/FAoDTVNQ
      ErcUEqwUEqkUCgpjYXJyaWVyTVNQEukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIr
      RENDQVo2Z0F3SUJBZ0lVQ2MrM2R1VXNxTmpGbW8reXpzenlEcTdHUjdRd0NnWUlLb1pJemowRUF3
      SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allY
      SnlhV1Z5TFc1bGREQWVGdzB5Ck1qRXlNekF3TkRFMU16bGFGdzB5TlRFd01Ua3dOREUxTXpsYU1G
      b3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJr
      eHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNt
      bGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBU3dmd3dMVGVYWnNv
      ZjFvb0dmb1hjQXQ3bnhXR0ozd3E0RzhkQ29MdGhNQk91ZjdrWDBXS3kzMTY3ZHdxalUKR1VuSzQz
      TVErQnpjZEFMb0psVGNLSXhsbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdF
      Qgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVvSzQ3S2t4a1Qva1VmV2dpTnlqc1F0VTlNTFl3Q2dZ
      SUtvWkl6ajBFCkF3SURTQUF3UlFJaEFNWSt6aFRQSFppSDJOU1l4NW5vSUErcHZ3RzZpbkt2QTg1
      T3AvN2dwRE5TQWlCWmRlUzcKSW9tTVFlQWFYd0pBMzhEc0pLTWpXVW5sYldHOFprWWRvN0NROUE9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKyCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlDN1RDQ0FwU2dBd0lCQWdJVU1jWlNiQyt0OHI5TG4wMFdLOHJTZmxDR2lnY3dDZ1lJS29a
      SXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1
      allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakV5TXpBd05ESXhNREJhRncweU16RXlNekF3TkRJ
      Mk1EQmFNSGd4Q3pBSkJnTlZCQVlUQWtkQ01Sc3dHUVlEClZRUUhFeEkxTVM0MU1DOHRNQzR4TXk5
      TWIyNWtiMjR4RURBT0JnTlZCQW9UQjBOaGNuSnBaWEl4SGpBTUJnTlYKQkFzVEJXRmtiV2x1TUE0
      R0ExVUVDeE1IWTJGeWNtbGxjakVhTUJnR0ExVUVBd3dSUVdSdGFXNUFZMkZ5Y21sbApjaTF1WlhR
      d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTN0hxaUJ5MWI1eGdMOUMvR2h5S3B2
      CnJzVW5hNU00d0xNdVM2bjlMN0NjbnBzYlFlTUNhRFJWRlpPOGJtUHhjZUdlOHZMRGNFWEpKbmpv
      U3kyVHBiTW4KbzRJQkdEQ0NBUlF3RGdZRFZSMFBBUUgvQkFRREFnZUFNQXdHQTFVZEV3RUIvd1FD
      TUFBd0hRWURWUjBPQkJZRQpGQ2xWWU5McUwzaithdmpXNiswa0NON2t1NGlCTUI4R0ExVWRJd1FZ
      TUJhQUZLQ3VPeXBNWkUvNUZIMW9JamNvCjdFTFZQVEMyTUNRR0ExVWRFUVFkTUJ1Q0dXTmhMWFJ2
      YjJ4ekxUWTVORGhpTkRnM1pqWXRaSGR1ZW5vd2dZMEcKQ0NvREJBVUdCd2dCQklHQWV5SmhkSFJ5
      Y3lJNmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aQpPaUowY25WbElpd2lhR1l1
      UVdabWFXeHBZWFJwYjI0aU9pSmpZWEp5YVdWeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1CmRFbEVJam9p
      UVdSdGFXNUFZMkZ5Y21sbGNpMXVaWFFpTENKb1ppNVVlWEJsSWpvaVlXUnRhVzRpZlgwd0NnWUkK
      S29aSXpqMEVBd0lEUndBd1JBSWdZREpyZCtkWndZVDdBc3BJeE5uQ21zeDQxYjA2WDhBeFVBd1h6
      NGhCY0o0QwpJRlJUWkZsVi9OZDZOQXh0WHZoNWg1M0tMK05aa2llSzZKY1ZpQUo3VXRwQgotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVDYyszZHVVc3FOakZtbyt5enN6eURxN0dS
      N1F3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dG
      UVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpFeU16QXdOREUxTXpsYUZ3MHlO
      VEV3TVRrd05ERTFNemxhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWti
      MjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdB
      MVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3
      TkMKQUFTd2Z3d0xUZVhac29mMW9vR2ZvWGNBdDdueFdHSjN3cTRHOGRDb0x0aE1CT3VmN2tYMFdL
      eTMxNjdkd3FqVQpHVW5LNDNNUStCemNkQUxvSmxUY0tJeGxvMEl3UURBUEJnTlZIUk1CQWY4RUJU
      QURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVW9LNDdLa3hrVC9rVWZX
      Z2lOeWpzUXRVOU1MWXdDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU1ZK3poVFBIWmlIMk5TWXg1
      bm9JQStwdndHNmluS3ZBODVPcC83Z3BETlNBaUJaZGVTNwpJb21NUWVBYVh3SkEzOERzSktNaldV
      bmxiV0c4WmtZZG83Q1E5QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiMwoH
      UmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0
      ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIq
      EiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50
      EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hh
      bm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdv
      cml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhAS
      Bgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNzZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHlj
      aGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYS
      DAoKCgZWMV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5z
      IiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoH
      V3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaCgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
