apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: solo

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.163.178.95:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIM4VKEgYy9w0PsttwX1oA1AdZRtunUXnM7j2P1DUfYc5ErpMCrdMCrRMCngKWggBEAEaBgju
      1dqdBiIKc3lzY2hhbm5lbCpAMGU2OGIzNjA1Njc1NWI5YTJmZTQ1ZWI1YzUzNWNiNmJhYzAxMGQ4
      NTJlZWI4MDQ4N2E0OGQ2OGZlZjlkY2M1MhIaEhgwLn5RheuVntpd3h9XmoPAT/1uMUg0J9ESt0sK
      tEsSsUsSqRkKB09yZGVyZXISnRkSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVQ2NCQVIydkIvZ2VZTC8wQ0N1bWtFcG9PZWljd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRBMU1UQXlPRFF4V2hjTk1qVXhNREkxTVRBeU9EUXhX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJQa250
      a3JzMndVSUw3V2FHK3ZQUnhhQUpzODI1R1ZkQk12cnBkUFR5MCtieU1EZXJiUGMKcTQ5NS8waGRC
      dUN5eDQwVXFsSXBNZkxvUW9ta3dyL2luT3lqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUzNLRU5mWitHK1V3YXVwZnRzaFJyTnFj
      Yng3ekFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlFQWgvdDd6eWFNbzB0ZmFLYXJhTG1JTDlSeUVG
      Z2RRNmN4d1pLUjd1QS8KOW80Q0h5KzJVSERqU3l3UWNWaWYxWlY1TnZmejhhWkIvS1ZBVUR6RzFK
      VFcyUG89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0RENDQW9lZ0F3SUJBZ0lVZUlheG5JZ3J6bEErS0d1U2NaWnFQSi9jT0NNd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRBMU1UQXpNVEF3V2hjTk1q
      UXdNVEExTVRBek5qQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFTFdTVk16MkUxUUl1SGhVamR4R01wSDVVWU1o
      SHBOeTcKcUcyYStvOHp4bEo4NStvNnFVcU00U252NDBjdWtUQy9Ra0pncXBIaHJXcEtIbFYwQ0pS
      OG82T0NBUk13Z2dFUApNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJRcUtzeGVYNkw2CnVyK1Q2MkRqbU9qeENsejcxekFmQmdOVkhTTUVHREFXZ0JT
      M0tFTmZaK0crVXdhdXBmdHNoUnJOcWNieDd6QWoKQmdOVkhSRUVIREFhZ2hoallTMTBiMjlzY3kx
      aU56Um1OVGczTnprdGREbHdhR2d3Z1lrR0NDb0RCQVVHQndnQgpCSDE3SW1GMGRISnpJanA3SW1G
      aVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlMQ0pvClppNUJabVpwYkds
      aGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNklrRmtiV2x1UUhOMWNIQnMKZVdO
      b1lXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURBZ05I
      QURCRQpBaUFuNzZNckt2enR2TG5rVTh4Y2RCUlhORzltWEdDMTIreU5HdDNieDhNSnJBSWdWVEt3
      WTZKcG9rdUdibkcvCjlZVHcvSkVjU0FwVE1pSGNJaHhIV2YyY2d4ND0KLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIvekNDQWFhZ0F3SUJBZ0lVQ2NCQVIydkIvZ2VZTC8wQ0N1bWtFcG9PZWljd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRBMU1UQXlPRFF4V2hjTk1qVXhNREkx
      TVRBeU9EUXhXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJQa250a3JzMndVSUw3V2FHK3ZQUnhhQUpzODI1R1ZkQk12cnBkUFR5MCtieU1EZXJiUGMK
      cTQ5NS8waGRCdUN5eDQwVXFsSXBNZkxvUW9ta3dyL2luT3lqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUzNLRU5mWitHK1V3YXVw
      ZnRzaFJyTnFjYng3ekFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlFQWgvdDd6eWFNbzB0ZmFLYXJh
      TG1JTDlSeUVGZ2RRNmN4d1pLUjd1QS8KOW80Q0h5KzJVSERqU3l3UWNWaWYxWlY1TnZmejhhWkIv
      S1ZBVUR6RzFKVFcyUG89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiNwoHUmVh
      ZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3Jp
      dGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJgoMQ2Fw
      YWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGiEKDUNvbnNlbnN1c1R5cGUSEBIGCgRz
      b2xvGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoGQWRtaW5z
      Er8vCgtDb25zb3J0aXVtcxKvLxLkLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsouEq4WCgpjYXJy
      aWVyTVNQEp8WGrsUCgNNU1ASsxQSqBQSpRQKCmNhcnJpZXJNU1AS5QUtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQjl6Q0NBWjZnQXdJQkFnSVVaRFRVVkRlSHd4ZVJadHA1UlpQQTJzbUkw
      NjB3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dG
      UVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBeE1EVXhNRE14TWpGYUZ3MHlO
      VEV3TWpVeE1ETXhNakZhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWti
      MjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdB
      MVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3
      TkMKQUFSUC94L2QvMnBtbG9kdy9CVnBJMzB0R0ZEZ1V4RjhVRlc0cFk0a0o4RjBKQkFUMFZHMk9T
      S3g3cDJ1R3ExUwp2bTFzWXdmNUNWdVRjM2M1czJRQkdKaTdvMEl3UURBUEJnTlZIUk1CQWY4RUJU
      QURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVWdSVHNQWEllQXZRbVhq
      bGQrcHIzc1hHVXlxd3dDZ1lJS29aSXpqMEUKQXdJRFJ3QXdSQUlnTzBkM3R3aXd5dU85N3I0TW9w
      enlreG50ckJXWjVVR2ZzU2pLM1ZuR05kd0NJSFpMbGREbQpWcXFITlZCd1FhQ3JSSDlyN2JseGdi
      QzhwdjZraXE5UGVBS0EKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lOIENF
      UlRJRklDQVRFLS0tLS0KTUlJQzdqQ0NBcFNnQXdJQkFnSVVRWTAzbktKVHQ5T0tKbE9MRVZLVGNx
      Nm9zUEl3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJr
      eHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1S
      Y3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBeE1EVXhNRE0wTURCYUZ3
      MHlOREF4TURVeE1ETTVNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1T
      NDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJB
      c1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJG
      eWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUy9rNXoweE5S
      MkVGalRuL1FIYjU0cQpiOUFGejN5UU03T1VuS1duMk9FWlVOQzFnVmwxRHNVVDViUnU3cXk3VzFh
      T0d3WFZ2Wm5HdmVDaXRVQ3dvb3FWCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3
      R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRk8ybXJWTU5WZVdEOHFtRGZXMWhMM2pjYXN4
      NU1COEdBMVVkSXdRWU1CYUFGSUVVN0QxeUhnTDBKbDQ1WGZxYQo5N0Z4bE1xc01DUUdBMVVkRVFR
      ZE1CdUNHV05oTFhSdmIyeHpMVFk1TkRoaU5EZzNaall0Wm1veVpqVXdnWTBHCkNDb0RCQVVHQndn
      QkJJR0FleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lK
      MGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhz
      YldWdQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0
      YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFNBQXdSUUloQU96V092ZUlGYnJueFQ5MEZzbTRhN2I5
      NFZQTERHYnFSWmwreUNRWjdtRFEKQWlCc2N4T0FHcFI3Rm5DVlh1Q1ZqRUYzR2I5bGFVeE9Oc0Nu
      cms1ZFcxL2tOZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkrl
      BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJVVpEVFVWRGVI
      d3hlUlp0cDVSWlBBMnNtSTA2MHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4
      RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFL
      REFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekF4
      TURVeE1ETXhNakZhRncweU5URXdNalV4TURNeE1qRmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdE
      UVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hR
      MkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9Q
      UUlCQmdncWhrak9QUU1CQndOQwpBQVJQL3gvZC8ycG1sb2R3L0JWcEkzMHRHRkRnVXhGOFVGVzRw
      WTRrSjhGMEpCQVQwVkcyT1NLeDdwMnVHcTFTCnZtMXNZd2Y1Q1Z1VGMzYzVzMlFCR0ppN28wSXdR
      REFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVG
      Z1FVZ1JUc1BYSWVBdlFtWGpsZCtwcjNzWEdVeXF3d0NnWUlLb1pJemowRQpBd0lEUndBd1JBSWdP
      MGQzdHdpd3l1Tzk3cjRNb3B6eWt4bnRyQldaNVVHZnNTakszVm5HTmR3Q0lIWkxsZERtClZxcUhO
      VkJ3UWFDclJIOXI3Ymx4Z2JDOHB2NmtpcTlQZUFLQQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      ChoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZB
      ZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1p
      bnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1p
      bnMiMwoHUmVhZGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyoG
      QWRtaW5zErsXCg9tYW51ZmFjdHVyZXJNU1ASpxcarxUKA01TUBKnFRKcFRKZFQoPbWFudWZhY3R1
      cmVyTVNQEoYGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEVENDQWJLZ0F3SUJBZ0lV
      RjhGSDl2MFhqUXRUQmQxMDR3Sm5nQlhXajcwd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVF
      QmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3
      RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBk
      WEpsCmNpMXVaWFF3SGhjTk1qTXdNVEExTVRBek1EQXlXaGNOTWpVeE1ESTFNVEF6TURBeVdqQmtN
      UXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFk
      WEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXVi
      V0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFC
      TlRiUnV4Y0NiQ2JVNDJrd0Q2SVh0Y0t0YUdzdlhDTXdabm0KalRJTDB4dGN3NUdjemQxdVpGa3NU
      dFpETlFCWFRqd2U5ZVBBSkYyajBrMEMyekd4bEcralFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJB
      Zjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlJWT3RRVlJ4TWFTR1c2Cmc3eTVU
      VWtSYkVDZnhUQUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUF4SXU5YjM0S1ROTFNwN3djRnJNNkpJ
      L2QKejg4QXFtd250ZFczeFhhMGJWZ0NJUURWZlkxRERQNTM1VU9HRVhPdWliOE9oZkoxbTBZWklG
      QTA0NDJIK0h3VApxdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIuMILS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQXJlZ0F3SUJBZ0lVSkl1TU54L3hJWlMvNjlBaFFDcVdI
      SmlYS0dNd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01C
      bHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpk
      SFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdN
      VEExTVRBek16QXdXaGNOTWpRd01UQTFNVEF6T0RBd1dqQ0JoakVMTUFrR0ExVUUKQmhNQ1EwZ3hH
      akFZQmdOVkJBY1RFVFEzTGpNNEx6Z3VOVFF2V25WeWFXTm9NUlV3RXdZRFZRUUtFd3hOWVc1MQpa
      bUZqZEhWeVpYSXhJekFNQmdOVkJBc1RCV0ZrYldsdU1CTUdBMVVFQ3hNTWJXRnVkV1poWTNSMWNt
      VnlNUjh3CkhRWURWUVFEREJaQlpHMXBia0J0WVc1MVptRmpkSFZ5WlhJdGJtVjBNRmt3RXdZSEtv
      Wkl6ajBDQVFZSUtvWkkKemowREFRY0RRZ0FFOUY4YWV4VXFGZUw5OEpMUmhzQXpXSnV4R1I0bWh5
      aEUxaWFua25SeW5wTW4vaWhKOXFETwpnTUxNYkMyK05ZSU0xUWVHbkRNTkNKWVBlMWJ1aytLTmo2
      T0NBU0l3Z2dFZU1BNEdBMVVkRHdFQi93UUVBd0lICmdEQU1CZ05WSFJNQkFmOEVBakFBTUIwR0Ex
      VWREZ1FXQkJTUXJ6a0dSdnMyRnVJYk5PNFVGY0t3bXhSRHNEQWYKQmdOVkhTTUVHREFXZ0JSVk90
      UVZSeE1hU0dXNmc3eTVUVWtSYkVDZnhUQWtCZ05WSFJFRUhUQWJnaGxqWVMxMApiMjlzY3kwMk9H
      UTVOVGRrWkRrMkxXdHljSHBrTUlHWEJnZ3FBd1FGQmdjSUFRU0JpbnNpWVhSMGNuTWlPbnNpCllX
      SmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdG
      MGFXOXUKSWpvaWJXRnVkV1poWTNSMWNtVnlJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdS
      dGFXNUFiV0Z1ZFdaaApZM1IxY21WeUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKaFpHMXBiaUo5ZlRB
      S0JnZ3Foa2pPUFFRREFnTklBREJGCkFpRUFrMXJVbk40MzYyTTVNUE1ZU2lVRXdyemlHNkZuU2hX
      ckoxSmhkb2wzM3pRQ0lGZ0NWaDFvTjY2b3FhdmcKT3NLTGNXM3hoU0Mzd3QzTnIyT29Bby9yc2JM
      QwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKhgYtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVGOEZIOXYwWGpRdFRCZDEwNHdK
      bmdCWFdqNzB3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFn
      TUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1G
      amRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpN
      d01UQTFNVEF6TURBeVdoY05NalV4TURJMU1UQXpNREF5V2pCa01Rc3dDUVlEVlFRRwpFd0pEU0RF
      UE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4RlRBVEJnTlZCQW9N
      CkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1poWTNSMWNtVnlMVzVs
      ZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJOVGJSdXhjQ2JDYlU0Mmt3RDZJ
      WHRjS3RhR3N2WENNd1pubQpqVElMMHh0Y3c1R2N6ZDF1WkZrc1R0WkROUUJYVGp3ZTllUEFKRjJq
      MGswQzJ6R3hsRytqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFE
      QWdHbU1CMEdBMVVkRGdRV0JCUlZPdFFWUnhNYVNHVzYKZzd5NVRVa1JiRUNmeFRBS0JnZ3Foa2pP
      UFFRREFnTkpBREJHQWlFQXhJdTliMzRLVE5MU3A3d2NGck02SkkvZAp6ODhBcW13bnRkVzN4WGEw
      YlZnQ0lRRFZmWTFERFA1MzVVT0dFWE91aWI4T2hmSjFtMFlaSUZBMDQ0MkgrSHdUCnF3PT0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAES
      AggAGhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggB
      EgIIABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggB
      EgIIABoVEhMKD21hbnVmYWN0dXJlck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAES
      HxIIEgYIARICCAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNoYW5u
      ZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      KhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3Jp
      dGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI
      /////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJlcjEuc3VwcGx5Y2hh
      aW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwK
      CgoGVjFfNF8zEgAaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIi
      CgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRt
      aW5zEAIaBkFkbWlucyoGQWRtaW5zGgoKAAoACgAKAAoA

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
