apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://20.205.142.40:8200
      role: vault-role
      authpath: localsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: upgrade.upgrade.com

    genesis: |-
      CiIaIEaCJMWA4JOI8vTL8Ez0NfspeutDeiUi9X2F2idhJxCTEqZeCqNeCqBeCngKWggBEAEaBgjG
      qvCdBiIKc3lzY2hhbm5lbCpAZGY5MTZhODg4ZjQ5MWQ1ODE3ODNkMWZhMzlhN2M2Yjg3YzY3MmYw
      NWY5ZDE2OGU3OGQ4ZDQxMzI1NGZkYzc0YhIaEhjsdnbRzqegCTA5oJwQdcwgSgG26AOX19ESo10K
      oF0SnV0SlysKB09yZGVyZXISiysSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVWk5KZC9DT2FnUVY3a2liOFlPNHZtS0hFYWVFd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRBNU1UTXhNakE0V2hjTk1qVXhNREk1TVRNeE1qQTRX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJCZmI3
      MkhRdDZmUGMybC9VYmVOWnZIZXZHT2VzZmZGSkJBdndoWS9XUjUzQWw1R0NST2cKNGhaVDZZT292
      ZUMvRGVnYktGUEYxUWtSN1o4dVhrY1hUL3VqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUW9tZmlUekNmdW4ycm51Vzhicjk1YWoz
      ZzJlakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCOWdISG9nVlVTVXdCNWtOSVdaMS9MR3JLM2dQ
      T3N1S1dlajdxYU82QS8Ka3dJaEFOUWZYQ0ZvUyt5ckhlQ2lYS25XakM5cHRZVjBOWlNoWkdNSXV3
      a3BDbVNVCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVZEN0azU2cytDQW8vTFFmMHRHYkNDa0c3bk9nd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nak13TVRBNU1UTXhNakF3V2hjTk1q
      UXdNVEE1TVRNeE56QXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFdGpUcUlxYWtraFNtcUdwMkFTYzZlZ3g2eWh3
      bEpNamYKQzRRVFl1cXZZODFvRmhjeDBIOFdscXp1R05GUHhLVnord3I3aVo2VElvejJiU3ljZG11
      NnBhT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJSaEh1YU1CMWlXCmVrekl1VGtJVWlRNWR6THB6ekFmQmdOVkhTTUVHREFXZ0JR
      b21maVR6Q2Z1bjJybnVXOGJyOTVhajNnMmVqQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      Mk9HWm1OMk0wWm1abUxXTndabTVxTUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQUoyenkwQ2tHUFVOeWZIQ2JrS2VQWlBoZ0JkK0NFNWVhSDdET1duVnU1b0dBaUFF
      VWdVcFZJMi9kcUlUCmpWNUk3eWoxMzNIdG9MRDhmUHVYaU1GMXdCcE83QT09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVVpOSmQvQ09hZ1FWN2tpYjhZTzR2bUtIRWFlRXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpNd01UQTVNVE14TWpBNFdoY05NalV4
      TURJNU1UTXhNakE0V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCQmZiNzJIUXQ2ZlBjMmwvVWJlTlp2SGV2R09lc2ZmRkpCQXZ3aFkvV1I1M0FsNUdD
      Uk9nCjRoWlQ2WU9vdmVDL0RlZ2JLRlBGMVFrUjdaOHVYa2NYVC91alFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlFvbWZpVHpDZnVu
      MnJudVc4YnI5NWFqM2cyZWpBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpQjlnSEhvZ1ZVU1V3QjVr
      TklXWjEvTEdySzNnUE9zdUtXZWo3cWFPNkEvCmt3SWhBTlFmWENGb1MreXJIZUNpWEtuV2pDOXB0
      WVYwTlpTaFpHTUl1d2twQ21TVQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlucxomCgxDYXBhYmlsaXRp
      ZXMSFhIMCgoKBlYxXzRfMhIAGgZBZG1pbnMaihIKDUNvbnNlbnN1c1R5cGUS+BES7REKCGV0Y2Ry
      YWZ0EuARCskRChhvcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQijca0wgtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJREJUQ0NBcXVnQXdJQkFnSVVhRjNIUDZDODJXK2JZUmJRWkNmcXBoNzFZ
      cjR3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dH
      UVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qTXdNVEE1TVRNeE1qQXdX
      aGNOTWpRd01UQTVNVE14TnpBd1dqQnhNUXN3Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNO
      VEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURW
      UVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJp
      MXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRUmxxdEIrWWU5dUd2ZUh6
      K2RXOGR0MGlrZgo0WXBrZjlIUlpET3RWOVVjSUFDUHZIdGlMdFhXQW53NFlzZ3RJenJwTFd0Rlk2
      b2NZWGtEb0pzalliOG5vNElCCk1qQ0NBUzR3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpR
      UVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0Ex
      VWREZ1FXQkJTQkJENEQycnRrZlRWVTFhckZtL2FYcWRjZwp6ekFmQmdOVkhTTUVHREFXZ0JRb21m
      aVR6Q2Z1bjJybnVXOGJyOTVhajNnMmVqQkJCZ05WSFJFRU9qQTRnaGh2CmNtUmxjbVZ5TVM1emRY
      QndiSGxqYUdGcGJpMXVaWFNDSEc5eVpHVnlaWEl4TG5Wd1ozSmhaR1V1ZFhCbmNtRmsKWlM1amIy
      MHdiQVlJS2dNRUJRWUhDQUVFWUhzaVlYUjBjbk1pT25zaWFHWXVRV1ptYVd4cFlYUnBiMjRpT2lJ
      aQpMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUp2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkx
      dVpYUWlMQ0pvClppNVVlWEJsSWpvaWIzSmtaWEpsY2lKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURC
      RkFpRUE3YS83elYwTXhoTGgKQ293V1NIdjd3Rjh2TjBuUU1LN2d4MVJmaFZLRHpvSUNJR1NONlUw
      Wm5ER2FqMUtwYmNWZHZnOTNqaTd1T0FWTApmd0h3MEJPdjZvL3QKLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQoi0wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJREJUQ0NBcXVnQXdJQkFn
      SVVhRjNIUDZDODJXK2JZUmJRWkNmcXBoNzFZcjR3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1S
      QXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkx
      dVpYUXcKSGhjTk1qTXdNVEE1TVRNeE1qQXdXaGNOTWpRd01UQTVNVE14TnpBd1dqQnhNUXN3Q1FZ
      RFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZ
      RFZRUUtFd2RQY21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXho
      dmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtq
      T1BRTUJCd05DQUFRUmxxdEIrWWU5dUd2ZUh6K2RXOGR0MGlrZgo0WXBrZjlIUlpET3RWOVVjSUFD
      UHZIdGlMdFhXQW53NFlzZ3RJenJwTFd0Rlk2b2NZWGtEb0pzalliOG5vNElCCk1qQ0NBUzR3RGdZ
      RFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFj
      REFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTQkJENEQycnRrZlRWVTFhckZtL2FY
      cWRjZwp6ekFmQmdOVkhTTUVHREFXZ0JRb21maVR6Q2Z1bjJybnVXOGJyOTVhajNnMmVqQkJCZ05W
      SFJFRU9qQTRnaGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDSEc5eVpHVnlaWEl4
      TG5Wd1ozSmhaR1V1ZFhCbmNtRmsKWlM1amIyMHdiQVlJS2dNRUJRWUhDQUVFWUhzaVlYUjBjbk1p
      T25zaWFHWXVRV1ptYVd4cFlYUnBiMjRpT2lJaQpMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUp2
      Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUWlMQ0pvClppNVVlWEJsSWpvaWIzSmtaWEps
      Y2lKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUE3YS83elYwTXhoTGgKQ293V1NIdjd3Rjh2
      TjBuUU1LN2d4MVJmaFZLRHpvSUNJR1NONlUwWm5ER2FqMUtwYmNWZHZnOTNqaTd1T0FWTApmd0h3
      MEJPdjZvL3QKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICAChoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFk
      bWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyoG
      QWRtaW5zEr0vCgtDb25zb3J0aXVtcxKtLxLiLgoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEsguErEX
      Cg9tYW51ZmFjdHVyZXJNU1ASnRcapRUKA01TUBKdFRKSFRKPFQoPbWFudWZhY3R1cmVyTVNQEoEG
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVVjE1clUybm1w
      VjBtRkJNWklPLzRERUJmb2w4d0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hE
      ekFOQmdOVkJBZ01CbHAxY21samFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtE
      QXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFCZ05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVa
      WFF3SGhjTk1qTXdNVEE1TVRNeE16STJXaGNOTWpVeE1ESTVNVE14TXpJMldqQmtNUXN3Q1FZRFZR
      UUcKRXdKRFNERVBNQTBHQTFVRUNBd0dXblZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZU
      QVRCZ05WQkFvTQpERTFoYm5WbVlXTjBkWEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkz
      UjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRlVMZDJ5MXlp
      em10a3NNQ1luVWZzRmh4clgvU2M2cmp4NXkKaVkyOUk5STBCQVg1Mzc2MmEybFFTcFJ0TitsTDdY
      eHV2OXBIeTlXb3RLWW95OGNmNWtHalFqQkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZS
      MFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlR6a1FVVytqWllVOVpyCm9xbU9XNUl3dCsyam5U
      QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFyY2trY0ZYVGRnTjl4R1RVa2FGM3dIVEQKMzJyL2h3
      WDNLSk1haFN5ZEs4b0NJR3MzeVJHY3N5MmJmYVhnQ0FjL1h4Q0dsdEErdG5kZVptbk40K2JwcXZk
      RAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLjCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlERVRDQ0FyZWdBd0lCQWdJVVN1aW1lWk1kS3VsQ1FEdGg0NGpnaHczUkd5a3dDZ1lJS29a
      SXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNtbGphREVQTUEw
      R0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpYSXhIREFhQmdO
      VkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nak13TVRBNU1UTXhOREF3V2hj
      Tk1qUXdNVEE1TVRNeE9UQXdXakNCaGpFTE1Ba0dBMVVFCkJoTUNRMGd4R2pBWUJnTlZCQWNURVRR
      M0xqTTRMemd1TlRRdlduVnlhV05vTVJVd0V3WURWUVFLRXd4TllXNTEKWm1GamRIVnlaWEl4SXpB
      TUJnTlZCQXNUQldGa2JXbHVNQk1HQTFVRUN4TU1iV0Z1ZFdaaFkzUjFjbVZ5TVI4dwpIUVlEVlFR
      RERCWkJaRzFwYmtCdFlXNTFabUZqZEhWeVpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJ
      CnpqMERBUWNEUWdBRW9pbk0yTy8yVFVjZzduWHhidDZiVHladzFycmo1TkdIbENqSzU4cXRtNUEy
      RW1YdThDR3MKR0NPU1BuWkpaWVhKeXo2R3duTjhEaTEyb3lPbVZKemZQYU9DQVNJd2dnRWVNQTRH
      QTFVZER3RUIvd1FFQXdJSApnREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCU2pLajk3
      emtrbkZhMzZnakdETXIzWVJoR1FRREFmCkJnTlZIU01FR0RBV2dCVHprUVVXK2paWVU5WnJvcW1P
      VzVJd3QrMmpuVEFrQmdOVkhSRUVIVEFiZ2hsallTMTAKYjI5c2N5MDJPRGhrWm1ZNE5UWTRMWG95
      YW5OME1JR1hCZ2dxQXdRRkJnY0lBUVNCaW5zaVlYUjBjbk1pT25zaQpZV0poWXk1cGJtbDBJam9p
      ZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1Cklqb2liV0Z1
      ZFdaaFkzUjFjbVZ5SWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaVFXUnRhVzVBYldGdWRXWmgK
      WTNSMWNtVnlMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSmhaRzFwYmlKOWZUQUtCZ2dxaGtqT1BRUURB
      Z05JQURCRgpBaUVBL3hIRDFYT3ovN2NYMzdodnNXYlIrWnE2VTFmeWhOZEd5YUpQQTdWMDRCY0NJ
      RjJwNTZhRnV0Y0J0K25oClo1YWNZVEg1TjhCb3AvRjNYbk1sSU02UDZOcmIKLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SoEGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSUNERENDQWJLZ0F3SUJBZ0lVVjE1clUybm1wVjBtRkJNWklPLzRERUJmb2w4d0NnWUlL
      b1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFERVBN
      QTBHQTFVRUJ3d0dXblZ5YVdObwpNUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5WlhJeEhEQWFC
      Z05WQkFNTUUyTmhMbTFoYm5WbVlXTjBkWEpsCmNpMXVaWFF3SGhjTk1qTXdNVEE1TVRNeE16STJX
      aGNOTWpVeE1ESTVNVE14TXpJMldqQmtNUXN3Q1FZRFZRUUcKRXdKRFNERVBNQTBHQTFVRUNBd0dX
      blZ5YVdOb01ROHdEUVlEVlFRSERBWmFkWEpwWTJneEZUQVRCZ05WQkFvTQpERTFoYm5WbVlXTjBk
      WEpsY2pFY01Cb0dBMVVFQXd3VFkyRXViV0Z1ZFdaaFkzUjFjbVZ5TFc1bGREQlpNQk1HCkJ5cUdT
      TTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRlVMZDJ5MXlpem10a3NNQ1luVWZzRmh4clgvU2M2cmp4
      NXkKaVkyOUk5STBCQVg1Mzc2MmEybFFTcFJ0TitsTDdYeHV2OXBIeTlXb3RLWW95OGNmNWtHalFq
      QkFNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERn
      UVdCQlR6a1FVVytqWllVOVpyCm9xbU9XNUl3dCsyam5UQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFp
      RUFyY2trY0ZYVGRnTjl4R1RVa2FGM3dIVEQKMzJyL2h3WDNLSk1haFN5ZEs4b0NJR3MzeVJHY3N5
      MmJmYVhnQ0FjL1h4Q0dsdEErdG5kZVptbk40K2JwcXZkRAotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChoGQWRtaW5zIjkKBkFkbWlucxIvEiUIARIhEggSBggBEgIIABoVEhMKD21hbnVmYWN0dXJl
      ck1TUBABGgZBZG1pbnMiPAoLRW5kb3JzZW1lbnQSLRIjCAESHxIIEgYIARICCAAaExIRCg9tYW51
      ZmFjdHVyZXJNU1AaBkFkbWlucyI4CgdSZWFkZXJzEi0SIwgBEh8SCBIGCAESAggAGhMSEQoPbWFu
      dWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHV3JpdGVycxItEiMIARIfEggSBggBEgIIABoTEhEKD21h
      bnVmYWN0dXJlck1TUBoGQWRtaW5zKgZBZG1pbnMSthYKCmNhcnJpZXJNU1ASpxYawxQKA01TUBK7
      FBKwFBKtFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RD
      Q0FaNmdBd0lCQWdJVVhVcmtGWFhFSHpqK3hMZi9rSFh4NE5zUGZKRXdDZ1lJS29aSXpqMEVBd0l3
      CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5
      YVdWeUxXNWxkREFlRncweQpNekF4TURreE16RTBORFJhRncweU5URXdNamt4TXpFME5EUmFNRm94
      Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2
      Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxs
      Y2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFXSmZ3d3dreXpkZ0I4
      WmlWaGNvT2ZRMXAvZ0RybjZmQ2tHUEpqUW5vQ0oxb3orMEhSNkJQbHlJaHBpMkw1Cm5PWE54VUtT
      Rm1oZ3NVZmVWRTNMU1RHZG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIK
      L3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVR0pIUXNLM3E1LzU0a3FxQmVZVFdGQTk3TkpBd0NnWUlL
      b1pJemowRQpBd0lEU0FBd1JRSWdPeEhrdlNMSVR3L0hWeTJsZDVJY2JsNkcxMlRUWlZ3MDdFdEcw
      cmRXY0dFQ0lRRCtxaDYzCmVDNFJnR3duNjBnTXNBVzRhU2YxZVBKcFJKWkV3NXpnT1pXUTNBPT0K
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQzdqQ0NBcFNnQXdJQkFnSVVaWGhJQ2I2ZlIxNWo2ZzN1TklGWnhqS3N4SG93Q2dZSUtvWkl6
      ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdB
      MVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZ
      UzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTXpBeE1Ea3hNekUxTURCYUZ3MHlOREF4TURreE16SXdN
      REJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1i
      MjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdB
      MVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUkV6K1hFbSt6VHdvK0w4alJwdlVPNAo3
      NUhLZjhMUGh2SnVtbHhhMkJJM3Q1MDVTbUYzVHVYVFNLR1VoTWdaY0xBUmFwUnd2ZnFrU3NYNUx2
      WEJBMXFFCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01B
      QXdIUVlEVlIwT0JCWUUKRkhrV1BZaWkxcS9vYk50OVdYRXdIeE1ycERScE1COEdBMVVkSXdRWU1C
      YUFGQmlSMExDdDZ1ZitlSktxZ1htRQoxaFFQZXpTUU1DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIy
      eHpMVGMyTkRsa09EaGtaall0Y2prMWFqa3dnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5
      STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFX
      Wm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFX
      UnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktv
      Wkl6ajBFQXdJRFNBQXdSUUloQU0rRnZSZ3ZHNDdBL2tQeXdDOS9mcm00TU5sUUZPaDdWdmRRZDFC
      TEQ3VTAKQWlBYmRTOVZodC95Mjh0WHBjTE15L0F6MGF0SWczcFI5dGRmWVZzRDZpaDlBZz09Ci0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVhVcmtGWFhFSHpqK3hMZi9rSFh4NE5z
      UGZKRXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJj
      d0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNekF4TURreE16RTBORFJhRncw
      eU5URXdNamt4TXpFME5EUmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1
      a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJV
      R0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1C
      QndOQwpBQVFXSmZ3d3dreXpkZ0I4WmlWaGNvT2ZRMXAvZ0RybjZmQ2tHUEpqUW5vQ0oxb3orMEhS
      NkJQbHlJaHBpMkw1Cm5PWE54VUtTRm1oZ3NVZmVWRTNMU1RHZG8wSXdRREFQQmdOVkhSTUJBZjhF
      QlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVR0pIUXNLM3E1LzU0
      a3FxQmVZVFdGQTk3TkpBd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdPeEhrdlNMSVR3L0hWeTJs
      ZDVJY2JsNkcxMlRUWlZ3MDdFdEcwcmRXY0dFQ0lRRCtxaDYzCmVDNFJnR3duNjBnTXNBVzRhU2Yx
      ZVBKcFJKWkV3NXpnT1pXUTNBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIz
      CgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFk
      bWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9y
      c2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1JlYWRl
      cnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVD
      aGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0Fk
      bWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0Fs
      Z29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUS
      EBIGCP////8PGgZBZG1pbnMaTgoQT3JkZXJlckFkZHJlc3NlcxI6Eh8KHW9yZGVyZXIxLnN1cHBs
      eWNoYWluLW5ldDo3MDUwGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMS
      FhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1p
      bnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoKCgAKAAoACgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
